### ISSUE TITLE
Template project codespace experience

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/evidence-vscode#46] opened 2023-05-31 20:28 UTC
This is not really a discrete feature vs a place to discuss this in public.

Taking inspiration from the [Malloy codespace](https://github.dev/malloydata/try-malloy/airports.malloy) which is excellent.

Some notes from @hughess 

> Was checking out Malloy’s extension again:
> They have a really smooth getting started path - maybe we should replicate
> - Theirs is click to “try Malloy in your browser now”
> - That opens a [github.dev](http://github.dev/) link, which takes you to codespace
> - Codespace is working right away, clicking to run a query brings up almost instant feedback

Would be great to get to an "everything just works" experience in Evidence template codespace. If we need to make changes to the template to support this, we can

**Comment by RandomFractals** [comment] 2023-06-01 00:24
What you see there is Malloy demo project using github.dev version of VS Code Web Editor that runs in a browser, and doesn't use Codespaces with containers to open a github project.

VS Code Web Editor is a limited version and doesn't support extensions that require `node.js` services or any other container services.

Until you have a `WASM` version of Evidence app dev runtime available, this will not be feasible in the short-term future.

You can read more about different version of VS Code Web Editor version here:

https://code.visualstudio.com/docs/editor/vscode-web

**Comment by RandomFractals** [comment] 2023-06-01 02:58
Closing this as a duplicate of #21. Please review our Codespaces integration in docs and the web editor notes above.

If you'd like to improve the current Evidence project onboarding experience using GitHub Codespaces I would recommend:

- you refine the current [`template`](https://github.com/evidence-dev/template) project `README.md`
- create new `try-evidence` branch in that template project
- or create new `try-evidence` project on github, with or without duckdb, etc.

We can link to the new simpler `try-evidence` project in our Codespaces docs in this extension.

**Closed by RandomFractals** 2023-06-01 02:58 UTC
Labels: design-ideas

**Comment by RandomFractals** [comment] 2023-06-01 10:59
As far as extension is concerned, the remaining "smooth" onboarding experience spit and polished will be addressed in https://github.com/evidence-dev/evidence-vscode/issues/10 next week. That ticket has sufficient planned feature details already too.
